### ISSUE TITLE
New Feature: Use models provided by the user

### ISSUE THREAD

**Issue by felipeZ** [nlesc-nano/swan#52]
## New
Allow the user to define her own models by providing the following information in the input file:

```yml
model:
   name: Model's_name
   parameters: to feed in the model
   path: Folder where the model is located
```
